### ISSUE TITLE
Postfix does log to to stdout

### ISSUE THREAD

**Issue by mjmayer** [juanluisbaptiste/docker-postfix#1]
It seems that postfix is supposed to be logging to /var/log/supervisor/postfix.log , which then should be accessible by using "docker logs $containername". The postfix.log file does not seem to be populated with log data.

I can't find any documentation that shows postfix can log to a file. It seems to only use syslog. I'm trying to troubleshoot an issue because my mail does not seem to be getting relayed. Log files would be helpful in troubleshooting.

**Comment by juanluisbaptiste** [comment]
Yes, that's true, PR's welcome :)

**Comment by rc1** [comment]
I'm having a similar issue; not sure where to start debugging. @mjmayer did you find a way?

**Comment by mjmayer** [comment]
@rc1 I never implemented a solution. postfix doesn't seem to have any way to log to stdout. I suppose that postfix could log to /var/maillog and part of the run supervisord script could be to tail -f /var/maillog.

**Comment by juanluisbaptiste** [comment]
sorry for the late reply. There's PR#2 that adds rsyslog to the container. I had hesitated on adding it because it should be possible to configure postfix to log to stdout/stderr instead, but I haven't found how yet (still doing some testing). 

I still think the best way is to make postfix log to stdout instead of adding a new component, but I also think that this needs to be fixed, so I think I will merge that PR for now while I find another way.

WDYT ?

**Comment by juanluisbaptiste** [comment]
Another option could be to use an additional rsyslog container, but postfix still would need to be configured to use the external one instead of trying to log to the local instance.

**Comment by juanluisbaptiste** [comment]
As I don't have time to look at how to make postfix log directly to stdout I added rsyslog support. Please test and reopen if there's another issue.

**Comment by varac** [comment]
Just driving by, here's the docs how to log to stdout: http://www.postfix.org/MAILLOG_README.html

**Comment by juanluisbaptiste** [comment]
The container currently logs to stout/stderr.
