### ISSUE TITLE
Getting the domain from the server host name

### ISSUE THREAD

**Issue by sjal** [juanluisbaptiste/docker-postfix#20]
This isn't so trivial as there are some cases like polish regional domains (eg. $DOMAIN.waw.pl) which should be interpreted as a whole, not just waw.pl (as this will not work correctly). This is something to consider as it currently forces me to do a workaround

**Comment by juanluisbaptiste** [comment]
Hi,

I really don't understand what's the issue, your report is un clear and vague at best. Could you explain with more details what is the problem ?

**Comment by juanluisbaptiste** [comment]
@sjal with the changes done for issue #16 there was a change on the way DOMAIN variable is calculated. If I understand correctly your issue is that if your host is for ex, _www.host.co.uk_, the current code will calculate the domain as _co.uk_ instead of _host.co.uk_ ? if yes then it is fixed in the new Alpine branch. 

Could you test `juanluisbaptiste/postfix:alpine` ?

**Comment by sjal** [comment]
Oh, cool. Thanks, I'll check it out. Sorry, I'm an avid GitLab user and I forgot about submitting an issue here

**Comment by sjal** [comment]
Hey, I've got the postfix:alpine version but it's all and the same:
`myhostname = foo.bar.pl`
`mydomain = bar.pl`
in `/etc/postfix/main.cf`

**Comment by sjal** [comment]
ah, sorry - i'm from one of these people that first write then check - I reinstalled the entire stack to test it out and wanted to send an email from otrs@localhost :) This is why it didn't work. I just checked my 'production' instance and it works like a charm, thanks!
